// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/my_song_model.dart';
import 'model/playlist_model.dart';
import 'model/song_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 668007825265052091),
    name: 'Song',
    lastPropertyId: const obx_int.IdUid(5, 3166716226409056261),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3978059592178831290),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6301132552975073782),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6320005701937599207),
        name: 'favorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5797442437404568959),
        name: 'number',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 2701213689850694877),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3166716226409056261),
        name: 'title',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3938641074242367669),
    name: 'MySong',
    lastPropertyId: const obx_int.IdUid(5, 1761442361365989912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3119382516938279091),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 518437909453992773),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8286221452805232626),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4549469558482212416),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1761442361365989912),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8329004716060602113),
    name: 'Playlist',
    lastPropertyId: const obx_int.IdUid(7, 3375595101226583881),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3242373538591484561),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2464759087458467895),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5960841246198653866),
        name: 'dateUtc',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7015428083183261362),
        name: 'colorKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5645087026474880424),
        name: 'iconKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8229112116457726011),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3375595101226583881),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6762238036192596406),
    name: 'PlaylistItem',
    lastPropertyId: const obx_int.IdUid(5, 32601841175332216),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7596483093264731890),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4725191247037845772),
        name: 'playlistId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 4419458840722104689),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 229300839838045429),
        name: 'songNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1870464081761425210),
        name: 'mySongId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 3572535006517445050),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 32601841175332216),
        name: 'position',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 6762238036192596406),
    lastIndexId: const obx_int.IdUid(3, 3572535006517445050),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Song: obx_int.EntityDefinition<Song>(
      model: _entities[0],
      toOneRelations: (Song object) => [],
      toManyRelations: (Song object) => {},
      getId: (Song object) => object.id,
      setId: (Song object, int id) {
        object.id = id;
      },
      objectToFB: (Song object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addBool(2, object.favorite);
        fbb.addInt64(3, object.number);
        fbb.addOffset(4, titleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final favoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final numberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = Song(
          id: idParam,
          content: contentParam,
          favorite: favoriteParam,
          number: numberParam,
          title: titleParam,
        );

        return object;
      },
    ),
    MySong: obx_int.EntityDefinition<MySong>(
      model: _entities[1],
      toOneRelations: (MySong object) => [],
      toManyRelations: (MySong object) => {},
      getId: (MySong object) => object.id,
      setId: (MySong object, int id) {
        object.id = id;
      },
      objectToFB: (MySong object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, contentOffset);
        fbb.addInt64(3, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(4, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0) / 1000)
              .round(),
        );
        final object = MySong(
          id: idParam,
          title: titleParam,
          content: contentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    Playlist: obx_int.EntityDefinition<Playlist>(
      model: _entities[2],
      toOneRelations: (Playlist object) => [],
      toManyRelations: (Playlist object) => {},
      getId: (Playlist object) => object.id,
      setId: (Playlist object, int id) {
        object.id = id;
      },
      objectToFB: (Playlist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final colorKeyOffset = fbb.writeString(object.colorKey);
        final iconKeyOffset = fbb.writeString(object.iconKey);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dateUtc?.millisecondsSinceEpoch);
        fbb.addOffset(3, colorKeyOffset);
        fbb.addOffset(4, iconKeyOffset);
        fbb.addInt64(5, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(6, object.updatedAt.microsecondsSinceEpoch * 1000);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateUtcValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateUtcParam = dateUtcValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateUtcValue);
        final colorKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final iconKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0) / 1000)
              .round(),
        );
        final updatedAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
        );
        final object = Playlist(
          id: idParam,
          name: nameParam,
          dateUtc: dateUtcParam,
          colorKey: colorKeyParam,
          iconKey: iconKeyParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    PlaylistItem: obx_int.EntityDefinition<PlaylistItem>(
      model: _entities[3],
      toOneRelations: (PlaylistItem object) => [],
      toManyRelations: (PlaylistItem object) => {},
      getId: (PlaylistItem object) => object.id,
      setId: (PlaylistItem object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistItem object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.playlistId);
        fbb.addInt64(2, object.songNumber);
        fbb.addInt64(3, object.mySongId);
        fbb.addInt64(4, object.position);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final playlistIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final songNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final mySongIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final positionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = PlaylistItem(
          id: idParam,
          playlistId: playlistIdParam,
          songNumber: songNumberParam,
          mySongId: mySongIdParam,
          position: positionParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// See [Song.id].
  static final id = obx.QueryIntegerProperty<Song>(_entities[0].properties[0]);

  /// See [Song.content].
  static final content = obx.QueryStringProperty<Song>(
    _entities[0].properties[1],
  );

  /// See [Song.favorite].
  static final favorite = obx.QueryBooleanProperty<Song>(
    _entities[0].properties[2],
  );

  /// See [Song.number].
  static final number = obx.QueryIntegerProperty<Song>(
    _entities[0].properties[3],
  );

  /// See [Song.title].
  static final title = obx.QueryStringProperty<Song>(
    _entities[0].properties[4],
  );
}

/// [MySong] entity fields to define ObjectBox queries.
class MySong_ {
  /// See [MySong.id].
  static final id = obx.QueryIntegerProperty<MySong>(
    _entities[1].properties[0],
  );

  /// See [MySong.title].
  static final title = obx.QueryStringProperty<MySong>(
    _entities[1].properties[1],
  );

  /// See [MySong.content].
  static final content = obx.QueryStringProperty<MySong>(
    _entities[1].properties[2],
  );

  /// See [MySong.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<MySong>(
    _entities[1].properties[3],
  );

  /// See [MySong.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<MySong>(
    _entities[1].properties[4],
  );
}

/// [Playlist] entity fields to define ObjectBox queries.
class Playlist_ {
  /// See [Playlist.id].
  static final id = obx.QueryIntegerProperty<Playlist>(
    _entities[2].properties[0],
  );

  /// See [Playlist.name].
  static final name = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[1],
  );

  /// See [Playlist.dateUtc].
  static final dateUtc = obx.QueryDateProperty<Playlist>(
    _entities[2].properties[2],
  );

  /// See [Playlist.colorKey].
  static final colorKey = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[3],
  );

  /// See [Playlist.iconKey].
  static final iconKey = obx.QueryStringProperty<Playlist>(
    _entities[2].properties[4],
  );

  /// See [Playlist.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<Playlist>(
    _entities[2].properties[5],
  );

  /// See [Playlist.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<Playlist>(
    _entities[2].properties[6],
  );
}

/// [PlaylistItem] entity fields to define ObjectBox queries.
class PlaylistItem_ {
  /// See [PlaylistItem.id].
  static final id = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[0],
  );

  /// See [PlaylistItem.playlistId].
  static final playlistId = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[1],
  );

  /// See [PlaylistItem.songNumber].
  static final songNumber = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[2],
  );

  /// See [PlaylistItem.mySongId].
  static final mySongId = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[3],
  );

  /// See [PlaylistItem.position].
  static final position = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[3].properties[4],
  );
}
